name: Run

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Pull dependencies
        run: yarn install

      - name: Run script
        run: yarn start

      - name: Upload raw data
        uses: actions/upload-artifact@v3
        with:
          name: output.json
          path: output.json

      - name: Upload grouped data
        uses: actions/upload-artifact@v3
        with:
          name: output-grouped.json
          path: output-grouped.json
