name: Run

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  runs-on: ubuntu-latest

  main:
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Pull dependencies
        run: yarn install

      - name: Run script
        run: yarn start

      - name: Upload output
        uses: actions/upload-artifact@v3
        with:
          name: output.json
          path: output.json
